### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by felipeloha** [subvisual/fsmx#9]
Hello

When will you be releasing the current master?
we would need the bugfix regarding the IO.inspect

thanks and kind regards

**Comment by egze** [comment]
@naps62 Can you please release 0.4.1? Are there any blockers?

**Comment by naps62** [comment]
@felipeloha @egze 
I just released 0.4.1

Sorry for the delay, I had some trouble setting up elixir on the new computer back when this issue was first created, and ended up forgetting to set a reminder for myself

I'll also be asking another coworker to help maintaining this alongside me. he's using Elixir daily, I have mostly moved on to other stacks :)
